# Generated by Django 5.1.4 on 2024-12-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('ML', 'Milk'), ('CR', 'Curd'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('cz', 'Cheese'), ('GH', 'Ghee'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
