# Generated by Django 5.1.4 on 2024-12-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('ML', 'Milk'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('CR', 'Curd'), ('cz', 'Cheese'), ('IC', 'Ice-Creams'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
