# Generated by Django 5.1.4 on 2024-12-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('PN', 'Paneer'), ('cz', 'Cheese'), ('IC', 'Ice-Creams'), ('GH', 'Ghee'), ('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
