# Generated by Django 5.1.4 on 2024-12-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LS', 'Lassi'), ('IC', 'Ice-Creams'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('ML', 'Milk'), ('PN', 'Paneer'), ('CR', 'Curd'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
