# Generated by Django 5.1.4 on 2024-12-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('IC', 'Ice-Creams'), ('CZ', 'Cheese'), ('ML', 'Milk')], max_length=2),
        ),
    ]
