# Generated by Django 5.1.4 on 2024-12-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('GH', 'Ghee'), ('CR', 'Curd'), ('ML', 'Milk'), ('PN', 'Paneer'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('CZ', 'Cheese')], max_length=2),
        ),
    ]
