# Generated by Django 5.1.4 on 2024-12-10 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('CR', 'Curd'), ('LS', 'Lassi'), ('ML', 'Milk'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('GH', 'Ghee')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('division', models.CharField(choices=[('Chittagong', 'Chittagong'), ('Mymensingh', 'Mymensingh'), ('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Barisal', 'Barisal'), ('Khulna', 'Khulna')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
