# Generated by Django 5.1.4 on 2024-12-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_product_category_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet'), ('Chittagong', 'Chittagong'), ('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Mymensingh', 'Mymensingh'), ('Barisal', 'Barisal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('CR', 'Curd'), ('ML', 'Milk'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
