# Generated by Django 5.1.4 on 2024-12-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Barisal', 'Barisal'), ('Chittagong', 'Chittagong'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Mymensingh', 'Mymensingh'), ('Dhaka', 'Dhaka'), ('Rangpur', 'Rangpur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('ML', 'Milk'), ('LS', 'Lassi'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('PN', 'Paneer'), ('MS', 'Milkshake'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
