# Generated by Django 5.1.4 on 2024-12-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Dhaka', 'Dhaka'), ('Mymensingh', 'Mymensingh'), ('Chittagong', 'Chittagong')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CR', 'Curd'), ('ML', 'Milk'), ('CZ', 'Cheese')], max_length=2),
        ),
    ]
