# Generated by Django 5.1.4 on 2024-12-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Barisal', 'Barisal'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Mymensingh', 'Mymensingh'), ('Rangpur', 'Rangpur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('MS', 'Milkshake'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('GH', 'Ghee'), ('ML', 'Milk'), ('LS', 'Lassi'), ('CR', 'Curd')], max_length=2),
        ),
    ]
