# Generated by Django 5.1.4 on 2024-12-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Dhaka', 'Dhaka')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('IC', 'Ice-Creams'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('MS', 'Milkshake'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
