# Generated by Django 5.1.4 on 2024-12-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Khulna', 'Khulna'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Mymensingh', 'Mymensingh'), ('Chittagong', 'Chittagong'), ('Dhaka', 'Dhaka'), ('Barisal', 'Barisal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LS', 'Lassi'), ('IC', 'Ice-Creams'), ('CR', 'Curd'), ('ML', 'Milk'), ('MS', 'Milkshake'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
