# Generated by Django 5.1.4 on 2024-12-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Mymensingh', 'Mymensingh'), ('Rangpur', 'Rangpur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('MS', 'Milkshake'), ('GH', 'Ghee'), ('ML', 'Milk'), ('CR', 'Curd'), ('IC', 'Ice-Creams'), ('PN', 'Paneer'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
