# Generated by Django 5.1.4 on 2024-12-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Barisal', 'Barisal'), ('Khulna', 'Khulna'), ('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet'), ('Mymensingh', 'Mymensingh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('MS', 'Milkshake'), ('ML', 'Milk'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('CR', 'Curd'), ('PN', 'Paneer'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
