# Generated by Django 5.1.4 on 2024-12-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Mymensingh', 'Mymensingh'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet'), ('Khulna', 'Khulna'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Dhaka', 'Dhaka'), ('Barisal', 'Barisal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LS', 'Lassi'), ('ML', 'Milk'), ('GH', 'Ghee'), ('PN', 'Paneer'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('CR', 'Curd'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
