# Generated by Django 5.1.4 on 2024-12-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Chittagong', 'Chittagong'), ('Mymensingh', 'Mymensingh'), ('Rangpur', 'Rangpur'), ('Barisal', 'Barisal'), ('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('PN', 'Paneer'), ('CZ', 'Cheese'), ('ML', 'Milk'), ('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('CR', 'Curd'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
