# Generated by Django 5.1.4 on 2024-12-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Sylhet', 'Sylhet'), ('Mymensingh', 'Mymensingh'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Rangpur', 'Rangpur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('GH', 'Ghee'), ('LS', 'Lassi'), ('ML', 'Milk'), ('PN', 'Paneer'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
