# Generated by Django 5.1.4 on 2024-12-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Chittagong', 'Chittagong'), ('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Dhaka', 'Dhaka'), ('Barisal', 'Barisal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('MS', 'Milkshake'), ('IC', 'Ice-Creams'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('ML', 'Milk')], max_length=2),
        ),
    ]
