# Generated by Django 5.1.3 on 2024-12-12 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_customer_division_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Barisal', 'Barisal'), ('Sylhet', 'Sylhet'), ('Khulna', 'Khulna'), ('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Chittagong', 'Chittagong'), ('Mymensingh', 'Mymensingh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('MS', 'Milkshake'), ('IC', 'Ice-Creams'), ('GH', 'Ghee'), ('LS', 'Lassi'), ('ML', 'Milk'), ('PN', 'Paneer'), ('CZ', 'Cheese')], max_length=2),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
