# Generated by Django 5.1.3 on 2024-12-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_customer_division_alter_product_category_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Mymensingh', 'Mymensingh'), ('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Dhaka', 'Dhaka'), ('Rangpur', 'Rangpur'), ('Khulna', 'Khulna')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Creams'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('ML', 'Milk'), ('GH', 'Ghee'), ('MS', 'Milkshake'), ('LS', 'Lassi'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
