# Generated by Django 5.1.3 on 2024-12-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Rangpur', 'Rangpur'), ('Dhaka', 'Dhaka'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('CR', 'Curd'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('ML', 'Milk')], max_length=2),
        ),
    ]
