# Generated by Django 5.1.3 on 2024-12-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Chittagong', 'Chittagong'), ('Sylhet', 'Sylhet'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('LS', 'Lassi'), ('IC', 'Ice-Creams'), ('ML', 'Milk'), ('MS', 'Milkshake'), ('GH', 'Ghee'), ('CR', 'Curd'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
