# Generated by Django 5.1.3 on 2024-12-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Mymensingh', 'Mymensingh'), ('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi'), ('Chittagong', 'Chittagong'), ('Sylhet', 'Sylhet'), ('Barisal', 'Barisal'), ('Dhaka', 'Dhaka'), ('Khulna', 'Khulna')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('ML', 'Milk'), ('CR', 'Curd')], max_length=2),
        ),
    ]
