# Generated by Django 5.1.3 on 2024-12-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet'), ('Barisal', 'Barisal'), ('Mymensingh', 'Mymensingh'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Creams'), ('CR', 'Curd'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('ML', 'Milk'), ('CZ', 'Cheese'), ('MS', 'Milkshake'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
