# Generated by Django 5.1.3 on 2024-12-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Dhaka', 'Dhaka'), ('Mymensingh', 'Mymensingh'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LS', 'Lassi'), ('PN', 'Paneer'), ('CR', 'Curd'), ('CZ', 'Cheese'), ('MS', 'Milkshake'), ('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('ML', 'Milk')], max_length=2),
        ),
    ]
