# Generated by Django 5.1.3 on 2024-12-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Sylhet', 'Sylhet'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Mymensingh', 'Mymensingh'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Chittagong', 'Chittagong'), ('Dhaka', 'Dhaka')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('IC', 'Ice-Creams'), ('ML', 'Milk'), ('LS', 'Lassi'), ('CR', 'Curd'), ('CZ', 'Cheese'), ('MS', 'Milkshake'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
