# Generated by Django 5.1.3 on 2024-12-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Khulna', 'Khulna'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Barisal', 'Barisal'), ('Sylhet', 'Sylhet'), ('Mymensingh', 'Mymensingh'), ('Rangpur', 'Rangpur'), ('Dhaka', 'Dhaka')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('GH', 'Ghee'), ('ML', 'Milk'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('IC', 'Ice-Creams'), ('CZ', 'Cheese'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
