# Generated by Django 5.1.3 on 2024-12-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Chittagong', 'Chittagong'), ('Sylhet', 'Sylhet'), ('Mymensingh', 'Mymensingh'), ('Dhaka', 'Dhaka')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('ML', 'Milk'), ('LS', 'Lassi'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
