# Generated by Django 5.1.3 on 2024-12-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Rangpur', 'Rangpur'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Chittagong', 'Chittagong'), ('Mymensingh', 'Mymensingh'), ('Barisal', 'Barisal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('IC', 'Ice-Creams'), ('GH', 'Ghee'), ('ML', 'Milk'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
