# Generated by Django 5.1.3 on 2024-12-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Mymensingh', 'Mymensingh'), ('Rangpur', 'Rangpur'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Sylhet', 'Sylhet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('CZ', 'Cheese'), ('ML', 'Milk'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
