# Generated by Django 5.1.3 on 2024-12-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Rangpur', 'Rangpur'), ('Barisal', 'Barisal'), ('Chittagong', 'Chittagong'), ('Mymensingh', 'Mymensingh'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('CR', 'Curd'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('ML', 'Milk'), ('CZ', 'Cheese'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
