# Generated by Django 5.1.3 on 2024-12-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Khulna', 'Khulna'), ('Dhaka', 'Dhaka'), ('Mymensingh', 'Mymensingh'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Chittagong', 'Chittagong'), ('Rangpur', 'Rangpur'), ('Barisal', 'Barisal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('LS', 'Lassi'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('GH', 'Ghee'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
