# Generated by Django 5.1.3 on 2024-12-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_customer_division_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Khulna', 'Khulna'), ('Chittagong', 'Chittagong'), ('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi'), ('Dhaka', 'Dhaka'), ('Sylhet', 'Sylhet'), ('Barisal', 'Barisal'), ('Mymensingh', 'Mymensingh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('GH', 'Ghee'), ('MS', 'Milkshake'), ('CR', 'Curd')], max_length=2),
        ),
    ]
