# Generated by Django 5.1.3 on 2024-12-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_customer_division_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Khulna', 'Khulna'), ('Mymensingh', 'Mymensingh'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi'), ('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Dhaka', 'Dhaka')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancle', 'Cancle')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('IC', 'Ice-Creams'), ('CR', 'Curd'), ('ML', 'Milk'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
