# Generated by Django 5.1.3 on 2024-12-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Rajshahi', 'Rajshahi'), ('Chittagong', 'Chittagong'), ('Mymensingh', 'Mymensingh'), ('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Khulna', 'Khulna')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On The Way', 'On The Way'), ('Accepted', 'Accepted'), ('Cancle', 'Cancle'), ('Packed', 'Packed'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('CR', 'Curd'), ('ML', 'Milk'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
