# Generated by Django 5.1.3 on 2024-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Mymensingh', 'Mymensingh'), ('Chittagong', 'Chittagong'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Barisal', 'Barisal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Cancle', 'Cancle'), ('Pending', 'Pending'), ('On The Way', 'On The Way'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('PN', 'Paneer'), ('ML', 'Milk'), ('IC', 'Ice-Creams'), ('CR', 'Curd'), ('MS', 'Milkshake'), ('LS', 'Lassi'), ('CZ', 'Cheese')], max_length=2),
        ),
    ]
