# Generated by Django 5.1.3 on 2024-12-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Khulna', 'Khulna'), ('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Mymensingh', 'Mymensingh'), ('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancle', 'Cancle'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('MS', 'Milkshake'), ('CR', 'Curd'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('ML', 'Milk'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
