# Generated by Django 5.1.3 on 2024-12-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Rajshahi', 'Rajshahi'), ('Mymensingh', 'Mymensingh'), ('Sylhet', 'Sylhet'), ('Barisal', 'Barisal'), ('Khulna', 'Khulna'), ('Dhaka', 'Dhaka'), ('Rangpur', 'Rangpur'), ('Chittagong', 'Chittagong')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Cancle', 'Cancle'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('On The Way', 'On The Way')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
