# Generated by Django 5.1.3 on 2024-12-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Barisal', 'Barisal'), ('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Chittagong', 'Chittagong'), ('Mymensingh', 'Mymensingh'), ('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Pending', 'Pending'), ('Cancle', 'Cancle'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('MS', 'Milkshake'), ('LS', 'Lassi'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('ML', 'Milk')], max_length=2),
        ),
    ]
