# Generated by Django 5.1.3 on 2024-12-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet'), ('Mymensingh', 'Mymensingh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Cancle', 'Cancle'), ('On The Way', 'On The Way'), ('Packed', 'Packed'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Creams'), ('CZ', 'Cheese'), ('MS', 'Milkshake'), ('ML', 'Milk'), ('GH', 'Ghee'), ('PN', 'Paneer'), ('CR', 'Curd'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
