# Generated by Django 5.1.3 on 2024-12-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Rangpur', 'Rangpur'), ('Barisal', 'Barisal'), ('Sylhet', 'Sylhet'), ('Mymensingh', 'Mymensingh'), ('Rajshahi', 'Rajshahi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Cancle', 'Cancle'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('CR', 'Curd'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('ML', 'Milk'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
