# Generated by Django 5.1.3 on 2024-12-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Mymensingh', 'Mymensingh'), ('Sylhet', 'Sylhet'), ('Khulna', 'Khulna'), ('Chittagong', 'Chittagong'), ('Dhaka', 'Dhaka'), ('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi'), ('Barisal', 'Barisal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Pending', 'Pending'), ('On The Way', 'On The Way'), ('Cancle', 'Cancle'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('ML', 'Milk'), ('PN', 'Paneer'), ('CR', 'Curd'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
