# Generated by Django 5.1.3 on 2024-12-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Barisal', 'Barisal'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Mymensingh', 'Mymensingh'), ('Chittagong', 'Chittagong'), ('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancle', 'Cancle'), ('On The Way', 'On The Way')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('GH', 'Ghee'), ('PN', 'Paneer'), ('ML', 'Milk'), ('LS', 'Lassi'), ('CR', 'Curd')], max_length=2),
        ),
    ]
