# Generated by Django 5.1.3 on 2024-12-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Chittagong', 'Chittagong'), ('Mymensingh', 'Mymensingh'), ('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On The Way', 'On The Way'), ('Packed', 'Packed'), ('Pending', 'Pending'), ('Cancle', 'Cancle'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('CZ', 'Cheese'), ('ML', 'Milk'), ('PN', 'Paneer'), ('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('LS', 'Lassi'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
