# Generated by Django 5.1.3 on 2024-12-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Rajshahi', 'Rajshahi'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Barisal', 'Barisal'), ('Dhaka', 'Dhaka'), ('Mymensingh', 'Mymensingh'), ('Rangpur', 'Rangpur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancle', 'Cancle'), ('Pending', 'Pending'), ('Packed', 'Packed'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('CR', 'Curd'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('ML', 'Milk'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
