# Generated by Django 5.1.4 on 2024-12-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Barisal', 'Barisal'), ('Chittagong', 'Chittagong')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('On The Way', 'On The Way'), ('Packed', 'Packed'), ('Cancle', 'Cancle')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('LS', 'Lassi'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('MS', 'Milkshake'), ('IC', 'Ice-Creams'), ('CR', 'Curd'), ('ML', 'Milk')], max_length=2),
        ),
    ]
