# Generated by Django 5.1.4 on 2024-12-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Dhaka', 'Dhaka'), ('Mymensingh', 'Mymensingh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancle', 'Cancle'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('ML', 'Milk'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
