# Generated by Django 5.1.4 on 2024-12-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Mymensingh', 'Mymensingh'), ('Chittagong', 'Chittagong'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Dhaka', 'Dhaka'), ('Barisal', 'Barisal'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Cancle', 'Cancle'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('PN', 'Paneer'), ('MS', 'Milkshake'), ('ML', 'Milk'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('CR', 'Curd')], max_length=2),
        ),
    ]
