# Generated by Django 5.1.4 on 2024-12-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Chittagong', 'Chittagong'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Cancle', 'Cancle'), ('Pending', 'Pending'), ('On The Way', 'On The Way'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('MS', 'Milkshake'), ('IC', 'Ice-Creams'), ('ML', 'Milk'), ('CR', 'Curd'), ('CZ', 'Cheese')], max_length=2),
        ),
    ]
