# Generated by Django 5.1.4 on 2024-12-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancle', 'Cancle'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('On The Way', 'On The Way')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('ML', 'Milk'), ('MS', 'Milkshake'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('CR', 'Curd')], max_length=2),
        ),
    ]
