# Generated by Django 5.1.4 on 2024-12-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Mymensingh', 'Mymensingh'), ('Dhaka', 'Dhaka'), ('Rangpur', 'Rangpur'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On The Way', 'On The Way'), ('Pending', 'Pending'), ('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Cancle', 'Cancle')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Creams'), ('CR', 'Curd'), ('ML', 'Milk'), ('CZ', 'Cheese'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
