# Generated by Django 5.1.4 on 2024-12-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Rajshahi', 'Rajshahi'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Dhaka', 'Dhaka'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Chittagong', 'Chittagong'), ('Sylhet', 'Sylhet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Cancle', 'Cancle'), ('Pending', 'Pending'), ('Packed', 'Packed'), ('On The Way', 'On The Way')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('LS', 'Lassi'), ('IC', 'Ice-Creams'), ('PN', 'Paneer'), ('CZ', 'Cheese'), ('MS', 'Milkshake'), ('GH', 'Ghee'), ('ML', 'Milk')], max_length=2),
        ),
    ]
