# Generated by Django 5.1.4 on 2024-12-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Dhaka', 'Dhaka'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Pending', 'Pending'), ('On The Way', 'On The Way'), ('Cancle', 'Cancle'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('ML', 'Milk'), ('PN', 'Paneer'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
