# Generated by Django 5.1.4 on 2024-12-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_alter_customer_division_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Dhaka', 'Dhaka'), ('Barisal', 'Barisal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Cancle', 'Cancle')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LS', 'Lassi'), ('IC', 'Ice-Creams'), ('ML', 'Milk'), ('CR', 'Curd'), ('MS', 'Milkshake'), ('GH', 'Ghee'), ('PN', 'Paneer'), ('CZ', 'Cheese')], max_length=2),
        ),
    ]
